### ISSUE TITLE
Use the .env file for the database URL (and others)

### ISSUE THREAD

**Issue by audreyteles** [Kryo098/fastAPI#1]
Hi,  I was looking at your code and found a way to improve it. Remember this is just a suggestion, but when you use the database connection, I think if you could use the dotenv library and instead of:

`ASYNC_DB_URL = "mysql+aiomysql://root@db:3306/demo?charset=utf8"`

I recommend:

`ASYNC_DB_URL = os.getenv("URL_DATABASE")`

So you can simplify your code and variables.

**Comment by Kryo098** [comment]
Hi, thank you kindly, I am still learning about Fast API and will take your suggestion into consideration!

**Comment by audreyteles** [comment]
I'm glad, if you need help, let me know.
